#!/bin/bash

# Updated attempt at curl notification script Number 3

FILE=~/Development/NAS/rss.xml

if [ -e "$FILE" ] || curl "https://feeds.noagendaassets.com/noagenda.xml" -o ~/Development/NAS/rss.xml; then
	echo "Fetching File"
  exit
fi
