#!/bin/bash

# Updated attempt at curl notification script Number 7
# Add touch to make file

FILE=~/Development/NAS/rss.xml
FILE2=~/Development/NAS/New_rss.xml

if [ -e "$FILE" ] || curl "https://feeds.noagendaassets.com/noagenda.xml" -o ~/Development/NAS/rss.xml; then
	echo "Fetching File"
fi
if [ -e "$FILE" ] && touch "$FILE2"; then
   echo "New File"
fi
if [ -e "$FILE2" ] && curl "https://feeds.noagendaassets.com/noagenda.xml" -o ~/Development/NAS/New_rss.xml; then
  echo "New Episode"
  exit
fi

exit
