#!/bin/bash

# Updated attempt at curl notification script Number 6
# Add touch to make file

FILE=~/Development/NAS/rss.xml
FILE2=~/Development/NAS/New_rss.xml

if [ -e "$FILE" ] || curl "https://feeds.noagendaassets.com/noagenda.xml" -o ~/Development/NAS/rss.xml; then
	echo "Fetching File"
  if [ -e "$FILE" ] && touch "$FILE2"; then
#    curl "https://feeds.noagendaassets.com/noagenda.xml" -o /Development/NAS/New_rss.xml; then
    echo "New File"
  fi
  exit
fi

#    [ -f "$FILE" ] && curl "https://feeds.noagendaassets.com/noagenda.xml" -o /Development/NAS/New_rss.xml; then
 #   echo "New File"
#  exit
#fi
#if [ -e "$FILE" ]; then
 # curl "https://feeds.noagendaassets.com/noagenda.xml" -o ~/Development/NAS/New_rss.xml; then
  #  echo "New File"
   # exit
#fi
 # echo "New File"
 # exit
#fi
