#!/bin/bash

# Script to fetch and alert when podcast episode is available

# Podcast URI
noagenda_rss="https://feeds.noagendaassets.com/noagenda.xml"
show="~/noagenda.xml"
current_show="$(curl $noagenda_rss -o ~/noagenda.xml)"

if [ ! -e $show ]; then
  $current_show && echo "Got the show!"
fi
